### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by ghost** [ownesis/librick-and-morty#1]
Hi bro. I love your ctf challenges, i want to learn from you. How can i reach you?

**Comment by ghost** [comment]
bruh :(

**Comment by ownesis** [comment]
@akhacorekhac Hi bro, what CTF are you talking about? And sorry, there is no way to reach me yet. Here is not appropriate, use the issues only if you have suggestions or spot a problem on the repository (librick-and-morty)

**Comment by ghost** [comment]
bro why dont you drop an email or something? i have your discord but i cant dm :(((

**Comment by ghost** [comment]
And sorry for opening this issue but  to be honest, i have no other way to reach you
